### ISSUE TITLE
Merge https://github.com/yaooqinn/kyuubi/blob/master/bin/kyuubi-logo to bin/kyuubi script

### ISSUE THREAD

**Issue by yaooqinn** [NetEase/kyuubi#517]
### 1. Describe the bug

kyuubi-logo is non-licensed

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0
  - [ ] 1.0.3
  - [ ] 0.8.x and earlier 

- Spark
  - [ ] 3.1.x
  - [ ] 3.0.x
  - [ ] 2.4.x and earlier 

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
@alex601049502 Would you like to pick this task?

**Comment by alex601049502** [comment]
Of course.Let me try.

**Comment by alex601049502** [comment]
#529
