### ISSUE TITLE
Deregister engine by itself by onJobFailed

### ISSUE THREAD

**Issue by yaooqinn** [NetEase/kyuubi#544]
### 1. Describe the feature

Introduce exception handling through JobFailed events to delete the engine by itself from the engine space. 

### 2. Motivation

This is useful for USER mode engines when some particular error occurred, such as token expiry, hardware failures, jar conflicts, which might lead to late coming queries doomed to fail. In this case, the engine should offline itself, and the new coming queries should be able to start a new engine to run and the old running queries also might be able to succeed via client retry.

### 3. Describe the solution

`kyuubi.engine.exception.class.for.deregister` - a seq for particular exception classes to notify engine to deregister
`kyuubi.engine.exception.message.for.deregister` -  a seq for particular exception messages to notify engine to deregister
`kyuubi.engine.exception.stacktrace.for.deregister` -  a seq for particular exception stacktraces to notify engine to deregister

Any of them matched the engine will deregister itself from the engine space, for example, `kyuubi.engine.exception.stacktrace.for.deregister` contains `org.apache.spark.executor.Executor.$anonfun$updateDependencies`

**Comment by yaooqinn** [comment]
WDYT, @pan3793 @turboFei @ulysses-you?

**Comment by turboFei** [comment]
Good feature, it is good for a long running service.

**Comment by pan3793** [comment]
Quite useful feature. And for the configuration keys, how about the following ones?
- `kyuubi.engine.deregister.exception.classes`
- `kyuubi.engine.deregister.exception.messages`
- `kyuubi.engine.deregister.exception.stacktraces`

The same prefix indicates that affects the same stuffs, and end with `s` to match `seq`

**Comment by yaooqinn** [comment]
I guess we can also add another conf like spark does for stages and task e.g. `spark.task.maxFailures`, `kyuubi.engine.job.max.failures` to deregister

**Comment by yaooqinn** [comment]
> Quite useful feature. And for the configuration keys, how about the following ones?
> 
> * `kyuubi.engine.deregister.exception.classes`
> * `kyuubi.engine.deregister.exception.messages`
> * `kyuubi.engine.deregister.exception.stacktraces`
> 
> The same prefix indicates that affects the same stuffs, and end with `s` to match `seq`

make sense

**Comment by turboFei** [comment]
> I guess we can also add another conf like spark does for stages and task e.g. `spark.task.maxFailures`, `kyuubi.engine.job.max.failures` to deregister

In further, is there a TTL for a failure.

For example, if an exception has been disappeared for 30 minutes, we think it has been recovered.

**Comment by yaooqinn** [comment]
> > I guess we can also add another conf like spark does for stages and task e.g. `spark.task.maxFailures`, `kyuubi.engine.job.max.failures` to deregister
> 
> In further, is there a TTL for a failure?
> `kyuubi.engine.deregister.exception.ttl`?
> For example, if an exception has been disappeared for 30 minutes, we think it has been recovered.

Make sense too
