### ISSUE TITLE
There is a small bug in the implementation GetOperationLogRowSet，Triggered in a synchronous Operation call

### ISSUE THREAD

**Issue by iodone** [NetEase/kyuubi#615]
### 1. Describe the bug
https://github.com/NetEase/kyuubi/blob/master/kyuubi-main/src/main/scala/org/apache/kyuubi/operation/KyuubiOperationManager.scala

```
override def getOperationLogRowSet(
      opHandle: OperationHandle,
      order: FetchOrientation, maxRows: Int): TRowSet = {

    val operation = getOperation(opHandle).asInstanceOf[KyuubiOperation]
    val operationLog = operation.getOperationLog
    operationLog match {
      case Some(log) => log.read(maxRows)
      case None =>
        val remoteHandle = operation.remoteOpHandle()
        val client = getThriftClient(operation.getSession.handle)

        if (remoteHandle != null) {
          val or = FetchOrientation.toTFetchOrientation(order)
          val req = new TFetchResultsReq(remoteHandle, or, maxRows)
          val resp = client.FetchResults(req)
          ThriftUtils.verifyTStatus(resp.getStatus)
          resp.getResults
        } else {
          ThriftUtils.EMPTY_ROW_SET
        }
    }
  }
```
The purpose of this method is to get the Operation Log, but the FetchType set in Req is equal to 0, which should be set to 1.
Because the problem will only occur in the call of the synchronization operation, but the operation log result API is generally not called in the synchronization scenario, the problem is more difficult to occur in actual use

#### 2.1 Versions

- Kyuubi
  - [ ] 1.1.0

### 3. Solution

Need to add a sentence `req.setFetchType(1.toShort)` before send the request.

**Comment by yaooqinn** [comment]
thanks for reporting this issue @iodone, can you send a PR to fix it?

**Comment by iodone** [comment]
Ok, i will fix it
