### ISSUE TITLE
How to import jar to spark classpath dynamically at startup

### ISSUE THREAD

**Issue by JinsYin** [NetEase/kyuubi#649]
Currently, I have to copy manually all jars (such as JDBC drivers) to `$SPARK_HOME/jars`  before the task starts. Is there a better solution?

**Comment by yaooqinn** [comment]
Using `spark.yarn.dist.jars` or SQL syntax `ADD JAR`

**Comment by JinsYin** [comment]
@yaooqinn Thanks so much!

**Comment by yaooqinn** [comment]
you are welcome
