### ISSUE TITLE
Better error msg and fast-fail during submitting engine

### ISSUE THREAD

**Issue by ulysses-you** [NetEase/kyuubi#668]
### 1. Describe the feature
* better error msg if encounter some issue with resource manager
* fast-fail as soon as possible 

### 2. Motivation
Currently Kyuubi will always wait `kyuubi.session.engine.initialize.timeout` time even if Spark app has already failed. The reason can be various. e.g. the permission issue, the env issue, the resource issue and so on.

### 3. Describe the solution
Enhance `ProcBuilder` and `SparkProcessBuilder`.

### 4. Additional context
For now, we focus on Spark on Yarn and can improve this with other resource managers in future.

**Comment by pan3793** [comment]
closed by #667
