### ISSUE TITLE
Can Kyuubi starts a Spark cluster in YARN cluster mode

### ISSUE THREAD

**Issue by zzchun** [NetEase/kyuubi#683]
Hi @xjzrc, can kyuubi starts a Spark YARN cluster in  cluster deployment mode ?

I tried by the following command, still starts a YARN cluster in client mode.

``` 
!connect jdbc:hive2://xxx:10009?spark.master=yarn;spark.deploy-mode=cluster;spark.yarn.queue=default;spark.app.name=my-app;
```

**Comment by yaooqinn** [comment]
spark.submit.deployMode?

**Comment by zzchun** [comment]
@yaooqinn `spark.submit.deployMode` works fine, thx !

**Comment by yaooqinn** [comment]
you're welcome.
