### ISSUE TITLE
authentication with ldap need to support both uid and cn ?

### ISSUE THREAD

**Issue by lordk911** [NetEase/kyuubi#709]
I'm using kyuubi-1.2.0-rc5. When I test authentication  with LDAP，I found that I need to  modify code : 
LdapAuthenticationProviderImpl.scala line:68 : 
![image](https://user-images.githubusercontent.com/19989300/123076830-103d7c00-d44c-11eb-8ddf-9037ab4abe20.png)

uid to cn , then I will connect to kyuubi success.

I'm not quite familiar with LDAP, maybe there will be some config property to identify use uid or cn ?

**Comment by yaooqinn** [comment]
I am not familiar with LDAP too. Can you help us check this on the HiveServer2 side? And then you may help us fix this issue

**Comment by lordk911** [comment]
> I am not familiar with LDAP too. Can you help us check this on the HiveServer2 side? And then you may help us fix this issue

I'm using HDP3.1.4 which hive version is 3.1.0, I've tested hiveserver2 ldap, through the source code I found there is a config property :

![image](https://user-images.githubusercontent.com/19989300/123086746-61eb0400-d456-11eb-89c6-5b342dcd69df.png)

after config this to cn, I can connect to hiveserver2, if use default value uid , faild

**Comment by yaooqinn** [comment]
maybe we should add this too, can you send a PR?
