### ISSUE TITLE
0A000: feature_not_supported

### ISSUE THREAD

**Issue by yaooqinn** [NetEase/kyuubi#728]
### 1. Describe the feature

Follow https://github.com/NetEase/kyuubi/issues/670 to: 
Apply `errorCode`  `0A000: feature_not_supported` to `val errStatus = KyuubiSQLException("Feature is not available").toTStatus`

### 3. Describe the solution

Add this to `KyuubiSQLException` object and use it wherever needed
```scala

  def featureNotSupported(): KyuubiSQLException = {
    KyuubiSQLException("feature not supported", sqlState = "0A000")
  }

```

**Comment by yaooqinn** [comment]
cc @zhaomin1423

**Comment by zhaomin1423** [comment]
> cc @zhaomin1423
I would like to do it.
