### ISSUE TITLE
How to integration with hive metastore 3.1.2

### ISSUE THREAD

**Issue by cutiechi** [NetEase/kyuubi#771]
### 1. Describe the bug

How to integration with hive metastore 3.1.2?

#### 2.1 Versions

- Kyuubi

  1.3-snapshot

- Spark
  3.1.2

#### 4.2 Log of the corresponding engine

**Comment by pan3793** [comment]
That can be find in spark docs 
https://spark.apache.org/docs/latest/sql-data-sources-hive-tables.html#interacting-with-different-versions-of-hive-metastore

**Comment by yaooqinn** [comment]
https://kyuubi.readthedocs.io/en/latest/deployment/hive_metastore.html

**Comment by cutiechi** [comment]
@yaooqinn @pan3793 LTGM
